 - different methods to create a dataset
 - reading dataset from external sources
 - basic insights of datasheet
 - selection of data
    - row wise selection
    - column wise selection
 - Data Cleaning and manupulation

In [281]:
import pandas as pd

In [282]:
movies={
    'title':['PK','RRR','I'],
    'year':[2024,2025,2026],
    'rating':[4.5,4.8,3.6]
}
df=pd.DataFrame(movies)
df

  title  year  rating
0    PK  2024     4.5
1   RRR  2025     4.8
2     I  2026     3.6

In [283]:
df= pd.read_csv("kc_house_data.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [284]:
df.head() #print top 5 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [285]:
df.tail() # bottom 5 row

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [286]:
df.head(7) # can be customized as per requirement

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819

In [287]:
df.tail(10)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21603,7852140040,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [288]:
df.sample() #pick any one  row randomly

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
16628,792000006,20140709T000000,187000.0,2,1.0,840,11600,1.0,0,0,...,6,840,0,1952,0,98168,47.492,-122.302,1610,9120

In [289]:
df.sample(5)# any random 5 rows (not sequential)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
591,3620069036,20141021T000000,265000.0,3,1.75,1820,32666,1.0,0,0,...,7,1820,0,1966,0,98022,47.1803,-121.974,2050,43560
14914,2622029073,20140905T000000,437500.0,3,2.25,2100,205603,2.0,0,0,...,8,2100,0,1983,0,98070,47.3668,-122.505,2396,187308
6608,2944000050,20150422T000000,995000.0,4,3.25,3530,20012,2.0,0,0,...,11,3530,0,1986,0,98052,47.7193,-122.127,3850,20707
13769,8732020770,20140904T000000,263850.0,4,2.25,2300,7524,2.0,0,0,...,8,2300,0,1978,0,98023,47.3130,-122.388,2270,8025
4040,8078350090,20150331T000000,619000.0,3,2.50,2040,7503,2.0,0,0,...,8,2040,0,1987,0,98029,47.5718,-122.021,2170,7503

In [290]:
df.info() # concise summaary

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [291]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [292]:
df.isnull()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21610,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21611,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21612,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [293]:
df.describe() # stastical summary

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [294]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [295]:
df.columns.tolist()

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

 - Row wise selection
    - iloc: index based selection
    - loc: label based selection
 - Column wise selection
    - single column selection
        - dictionary like
        - object like
    - multiple column selsction
        - dictionary like

In [296]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [297]:
df.iloc[0]# iloc gives the first row of a data column

id                    7129300520
date             20141013T000000
price                   221900.0
bedrooms                       3
bathrooms                    1.0
sqft_living                 1180
sqft_lot                    5650
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  1180
sqft_basement                  0
yr_built                    1955
yr_renovated                   0
zipcode                    98178
lat                      47.5112
long                    -122.257
sqft_living15               1340
sqft_lot15                  5650
Name: 0, dtype: object

In [298]:
df.iloc[5] # print 5 index value all information

id                    7237550310
date             20140512T000000
price                  1225000.0
bedrooms                       4
bathrooms                    4.5
sqft_living                 5420
sqft_lot                  101930
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                         11
sqft_above                  3890
sqft_basement               1530
yr_built                    2001
yr_renovated                   0
zipcode                    98053
lat                      47.6561
long                    -122.005
sqft_living15               4760
sqft_lot15                101930
Name: 5, dtype: object

In [299]:
df.iloc[-7] #iloc works with negative indexing too

id                    7936000429
date             20150326T000000
price                  1007500.0
bedrooms                       4
bathrooms                    3.5
sqft_living                 3510
sqft_lot                    7200
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          9
sqft_above                  2600
sqft_basement                910
yr_built                    2009
yr_renovated                   0
zipcode                    98136
lat                      47.5537
long                    -122.398
sqft_living15               2050
sqft_lot15                  6200
Name: 21606, dtype: object

In [300]:
df.iloc[1:6] # iloc works with slicing

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930

In [301]:
df.iloc[1:11:3]#slicing in iloc

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
10,1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925

In [302]:
df.iloc[[3,5,1,2,9]]# for specific rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

In [303]:
df.iloc[[11,21],[9,8]] # for specific rows and column too

    view  waterfront
11     0           0
21     4           0

In [304]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [305]:
df=df.set_index("id")
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

loc

In [306]:
df.loc[6600060120]

date             20150223T000000
price                   400000.0
bedrooms                       4
bathrooms                    2.5
sqft_living                 2310
sqft_lot                    5813
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          8
sqft_above                  2310
sqft_basement                  0
yr_built                    2014
yr_renovated                   0
zipcode                    98146
lat                      47.5107
long                    -122.362
sqft_living15               1830
sqft_lot15                  7200
Name: 6600060120, dtype: object

In [307]:
df.loc[7129300520:263000018]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,3,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,3,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
7936000429,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,3,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,3,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509

In [308]:
df.loc[:1954400510]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [309]:
df.loc[[2487200875,7936000429]]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
2487200875,20141209T000000,604000.0,4,3.0,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
7936000429,20150326T000000,1007500.0,4,3.5,3510,7200,2.0,0,0,3,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200

DATA CLEANING
- dropping rows and columns
- renaming columns name
-  changing data type of a column
- dropping missing values
- handling missing values
- checking duplicates
- dropping duplicates
- checking unique values
- count of unique values
- frequency count of a value
- sorting values

In [310]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [311]:
df['price']

id
7129300520    221900.0
6414100192    538000.0
5631500400    180000.0
2487200875    604000.0
1954400510    510000.0
                ...
263000018     360000.0
6600060120    400000.0
1523300141    402101.0
291310100     400000.0
1523300157    325000.0
Name: price, Length: 21613, dtype: float64

In [312]:
df.get("price")

id
7129300520    221900.0
6414100192    538000.0
5631500400    180000.0
2487200875    604000.0
1954400510    510000.0
                ...
263000018     360000.0
6600060120    400000.0
1523300141    402101.0
291310100     400000.0
1523300157    325000.0
Name: price, Length: 21613, dtype: float64

In [313]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [314]:
df.drop(columns=['sqft_living15', 'sqft_lot15'])#drop columns

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299

In [315]:
df.drop (labels=[7129300520],inplace=True)#drop rows with id

In [316]:
df.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930

In [317]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [318]:
df=df.astype({'bedrooms':'float64'})
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4.0,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3.0,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4.0,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2.0,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3.0,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2.0,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [319]:
renamed_cols={
    'lat':'latitude',
    'long':'longitude'
}
df = df.rename(columns=renamed_cols)

In [320]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,latitude,longitude,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4.0,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3.0,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4.0,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2.0,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3.0,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2.0,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [321]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

- When a column has <40% missing values of the data, then we simply remove that  column
- When a column has >40% missing values of data, then we handle those missing values means we replace those missing values with any number
    - there are teo type of columns in any dataset - CATAGORICAL & NUMERICAL
    - When the column is numerical, we always repalce the null values with the column mean(average)
    - When the column is categorical, we always replace the null values with most frequent(mode) values

In [322]:
titanic=sns.load_dataset('titanic')
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [323]:
titanic=titanic.dropna(subset=['embarked'])# dropna deletes the null rows automatically
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [324]:
# calculate the average age of passenger in the titanic dataset
avg_age=round(titanic['age'].mean()) #round is used to round the value, 
print(avg_age)                               #mean is used to calculate the average

30

In [325]:
#replace null values with avg_age
titanic['age']=titanic['age'].fillna(avg_age)# handle nulll values 
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [326]:
#checking duplicates
duplicates=titanic[titanic.duplicated()]
print(duplicates)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
47          1       3  female  30.0      0      0   7.7500        Q   Third
76          0       3    male  30.0      0      0   7.8958        S   Third
77          0       3    male  30.0      0      0   8.0500        S   Third
87          0       3    male  30.0      0      0   8.0500        S   Third
95          0       3    male  30.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
870         0       3    male  26.0      0      0   7.8958        S   Third
877         0       3    male  19.0      0      0   7.8958        S   Third
878         0       3    male  30.0      0      0   7.8958        S   Third
884         0       3    male  25.0      0      0   7.0500        S   Third
886         0       2    male  27.0      0      0  13.0000        S  Second

       who  adult_male deck  embark_town alive  alone
47   woman       False  NaN   Queenstown   yes   True
76     man        True  NaN  Southampton    no   True
77     man        True  NaN  Southampton    no   True
87     man        True  NaN  Southampton    no   True
95     man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
870    man        True  NaN  Southampton    no   True
877    man        True  NaN  Southampton    no   True
878    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True

[113 rows x 15 columns]

In [327]:
#dropping duplicates
titanic.drop_duplicates()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [328]:
titanic['age'].unique()

array([22.  , 38.  , 26.  , 35.  , 30.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [329]:
#frequence of values in a categorial column
titanic['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [330]:
titanic['embark_town'].value_counts().idxmax()

'Southampton'

In [331]:
titanic['embark_town'].value_counts().idxmin()

'Queenstown'

In [332]:
titanic.sort_index()# used to sort id which we set as index before

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

DATA MANIPULATION

In [333]:
#Adding a new column
titanic = titanic.assign(Discount=titanic['fare']*0.10)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [334]:
titanic['fare'] = titanic['fare'].apply(lambda x:x*1.05)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [335]:
titanic['embarked']=titanic['embarked'].map({
    "S":"Southampton",
    "C":"Cherbourg",
    "Q":"Queenstown"
})
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,Southampton,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,Southampton,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,Southampton,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,Cherbourg,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.77500

In [336]:
titanic.groupby("embarked")['fare'].mean()

embarked
Cherbourg      62.951851
Queenstown     13.939831
Southampton    28.433802
Name: fare, dtype: float64

In [337]:
titanic.groupby("sex")['fare'].max()

sex
female    537.94566
male      537.94566
Name: fare, dtype: float64

In [338]:
#data filtering
titanic[titanic['survived']==0]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,Southampton,Third,man,True,NaN,Southampton,no,False,0.72500
4,0,3,male,35.0,0,0,8.452500,Southampton,Third,man,True,NaN,Southampton,no,True,0.80500
5,0,3,male,30.0,0,0,8.881215,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.84583
6,0,1,male,54.0,0,0,54.455625,Southampton,First,man,True,E,Southampton,no,True,5.18625
7,0,3,male,2.0,3,1,22.128750,Southampton,Third,child,False,NaN,Southampton,no,False,2.10750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.402500,Southampton,Third,man,True,NaN,Southampton,no,True,0.70500
885,0,3,female,39.0,0,5,30.581250,Queenstown,Third,woman,False,NaN,Queenstown,no,False,2.91250
886,0,2,male,27.0,0,0,13.650000,Southampton,Second,man,True,NaN,Southampton,no,True,1.30000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500
890,0,3,male,32.0,0,0,8.137500,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.77500

In [339]:
titanic[titanic['sex']=='female']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
8,1,3,female,27.0,0,2,11.689965,Southampton,Third,woman,False,NaN,Southampton,yes,False,1.11333
9,1,2,female,14.0,1,0,31.574340,Cherbourg,Second,child,False,NaN,Cherbourg,yes,False,3.00708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,27.300000,Southampton,Second,woman,False,NaN,Southampton,yes,False,2.60000
882,0,3,female,22.0,0,0,11.042535,Southampton,Third,woman,False,NaN,Southampton,no,True,1.05167
885,0,3,female,39.0,0,5,30.581250,Queenstown,Third,woman,False,NaN,Queenstown,no,False,2.91250
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500

In [340]:
#sorting values
titanic.sort_values("fare",ascending=False)#false arrange data in desending to ascending
                                           #true arrange the data in ascending to descending

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
679,1,1,male,36.0,0,1,537.94566,Cherbourg,First,man,True,B,Cherbourg,yes,False,51.23292
258,1,1,female,35.0,0,0,537.94566,Cherbourg,First,woman,False,NaN,Cherbourg,yes,True,51.23292
737,1,1,male,35.0,0,0,537.94566,Cherbourg,First,man,True,B,Cherbourg,yes,True,51.23292
341,1,1,female,24.0,3,2,276.15000,Southampton,First,woman,False,C,Southampton,yes,False,26.30000
88,1,1,female,23.0,3,2,276.15000,Southampton,First,woman,False,C,Southampton,yes,False,26.30000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,0,3,male,36.0,0,0,0.00000,Southampton,Third,man,True,NaN,Southampton,no,True,0.00000
263,0,1,male,40.0,0,0,0.00000,Southampton,First,man,True,B,Southampton,no,True,0.00000
277,0,2,male,30.0,0,0,0.00000,Southampton,Second,man,True,NaN,Southampton,no,True,0.00000
815,0,1,male,30.0,0,0,0.00000,Southampton,First,man,True,B,Southampton,no,True,0.00000
822,0,1,male,38.0,0,0,0.00000,Southampton,First,man,True,NaN,Southampton,no,True,0.00000

# SLEEP

In [341]:
import pandas as pd

In [342]:
sleep=pd.read_csv("dataset_2191_sleep.csv")

In [343]:
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [344]:
sleep.head()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9

In [345]:
sleep.tail()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [346]:
sleep.head(21)

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
5,10.550,179.5,27,180,4,4,4,9.8
6,0.023,0.3,19,35,1,1,1,19.7
7,160.000,169.0,30.4,392,4,5,4,6.2
8,3.300,25.6,28,63,1,2,1,14.5
9,52.160,440.0,50,230,1,1,1,9.7
10,0.425,6.4,7,112,5,4,4,12.5
11,465.000,423.0,30,281,5,5,5,3.9
12,0.550,2.4,?,?,2,1,2,10.3
13,187.100,419.0,40,365,5,5,5,3.1
14,0.075,1.2,3.5,42,1,1,1,8.4
15,3.000,25.0,50,28,2,2,2,8.6
16,0.785,3.5,6,42,2,2,2,10.7
17,0.200,5.0,10.4,120,2,2,2,10.7
18,1.410,17.5,34,?,1,2,1,6.1
19,60.000,81.0,7,?,1,1,1,18.1
20,529.000,680.0,28,400,5,5,5,?

In [347]:
sleep.tail(7)

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
55,0.060,1.0,3.5,?,3,1,2,10.3
56,0.900,2.6,4.5,60,2,1,2,13.3
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [348]:
sleep.sample()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
3,0.92,5.7,?,25,5,2,3,16.5

In [349]:
sleep.sample(9)

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
49,6.800,179.00,29,164,2,3,2,9.6
26,0.101,4.00,9,28,5,1,3,13.8
22,0.120,1.00,3.9,16,3,1,2,14.4
9,52.160,440.00,50,230,1,1,1,9.7
32,0.010,0.25,24,50,1,1,1,19.9
59,4.190,58.00,24,210,4,3,4,10.3
17,0.200,5.00,10.4,120,2,2,2,10.7
50,0.750,12.30,7,225,2,2,2,6.6
6,0.023,0.30,19,35,1,1,1,19.7

In [350]:
sleep.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   body_weight           62 non-null     float64
 1   brain_weight          62 non-null     float64
 2   max_life_span         62 non-null     str
 3   gestation_time        62 non-null     str
 4   predation_index       62 non-null     int64
 5   sleep_exposure_index  62 non-null     int64
 6   danger_index          62 non-null     int64
 7   total_sleep           62 non-null     str
dtypes: float64(2), int64(3), str(3)
memory usage: 4.0 KB

In [351]:
sleep.isnull().sum()

body_weight             0
brain_weight            0
max_life_span           0
gestation_time          0
predation_index         0
sleep_exposure_index    0
danger_index            0
total_sleep             0
dtype: int64

In [352]:
sleep.isnull()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False

In [353]:
sleep.describe()

,body_weight,brain_weight,predation_index,sleep_exposure_index,danger_index
count,62.000000,62.000000,62.000000,62.000000,62.000000
mean,198.789984,283.134194,2.870968,2.419355,2.612903
std,899.158011,930.278942,1.476414,1.604792,1.441252
min,0.005000,0.140000,1.000000,1.000000,1.000000
25%,0.600000,4.250000,2.000000,1.000000,1.000000
50%,3.342500,17.250000,3.000000,2.000000,2.000000
75%,48.202500,166.000000,4.000000,4.000000,4.000000
max,6654.000000,5712.000000,5.000000,5.000000,5.000000

In [354]:
sleep.columns

Index(['body_weight', 'brain_weight', 'max_life_span', 'gestation_time',
       'predation_index', 'sleep_exposure_index', 'danger_index',
       'total_sleep'],
      dtype='str')

In [355]:
sleep.columns.tolist()

['body_weight',
 'brain_weight',
 'max_life_span',
 'gestation_time',
 'predation_index',
 'sleep_exposure_index',
 'danger_index',
 'total_sleep']

In [356]:
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [357]:
sleep.iloc[5]

body_weight             10.55
brain_weight            179.5
max_life_span              27
gestation_time            180
predation_index             4
sleep_exposure_index        4
danger_index                4
total_sleep               9.8
Name: 5, dtype: object

In [358]:
sleep.iloc[-7]

body_weight             0.06
brain_weight             1.0
max_life_span            3.5
gestation_time             ?
predation_index            3
sleep_exposure_index       1
danger_index               2
total_sleep             10.3
Name: 55, dtype: object

In [242]:
sleep.iloc[1:11]

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
5,10.550,179.5,27,180,4,4,4,9.8
6,0.023,0.3,19,35,1,1,1,19.7
7,160.000,169.0,30.4,392,4,5,4,6.2
8,3.300,25.6,28,63,1,2,1,14.5
9,52.160,440.0,50,230,1,1,1,9.7
10,0.425,6.4,7,112,5,4,4,12.5

In [243]:
sleep.iloc[1:11:9]

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
1,1.000,6.6,4.5,42,3,1,3,8.3
10,0.425,6.4,7,112,5,4,4,12.5

In [244]:
sleep.iloc[::11]

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.00,5712.0,38.6,645,3,5,3,3.3
11,465.00,423.0,30,281,5,5,5,3.9
22,0.12,1.0,3.9,16,3,1,2,14.4
33,62.00,1320.0,100,267,1,1,1,8
44,192.00,180.0,27,115,4,4,4,8.4
55,0.06,1.0,3.5,?,3,1,2,10.3

In [245]:
sleep.iloc[[2,4,6,8,10]]

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
2,3.385,44.5,14,60,1,1,1,12.5
4,2547.000,4603.0,69,624,3,5,4,3.9
6,0.023,0.3,19,35,1,1,1,19.7
8,3.300,25.6,28,63,1,2,1,14.5
10,0.425,6.4,7,112,5,4,4,12.5

In [246]:
sleep.iloc[[11,21],[1,3]]

    brain_weight gestation_time
11         423.0            281
21         115.0            148

In [247]:
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [248]:
sleeps=sleep.set_index("body_weight")
sleeps

,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
body_weight,,,,,,,
6654.000,5712.0,38.6,645,3,5,3,3.3
1.000,6.6,4.5,42,3,1,3,8.3
3.385,44.5,14,60,1,1,1,12.5
0.920,5.7,?,25,5,2,3,16.5
2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...
2.000,12.3,7.5,200,3,1,3,5.4
0.104,2.5,2.3,46,3,2,2,15.8
4.190,58.0,24,210,4,3,4,10.3
3.500,3.9,3,14,2,1,1,19.4
4.050,17.0,13,38,3,1,1,?

In [249]:
print(sleeps.shape)

(62, 7)

In [250]:
print("rows",sleep.shape[0])
print("columns",sleep.shape[1])

rows 62
columns 8

In [251]:
sleeps

,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
body_weight,,,,,,,
6654.000,5712.0,38.6,645,3,5,3,3.3
1.000,6.6,4.5,42,3,1,3,8.3
3.385,44.5,14,60,1,1,1,12.5
0.920,5.7,?,25,5,2,3,16.5
2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...
2.000,12.3,7.5,200,3,1,3,5.4
0.104,2.5,2.3,46,3,2,2,15.8
4.190,58.0,24,210,4,3,4,10.3
3.500,3.9,3,14,2,1,1,19.4
4.050,17.0,13,38,3,1,1,?

In [252]:
sleeps.loc[2547.000]

brain_weight            4603.0
max_life_span               69
gestation_time             624
predation_index              3
sleep_exposure_index         5
danger_index                 4
total_sleep                3.9
Name: 2547.0, dtype: object

In [253]:
sleeps.loc[3]

brain_weight            25.0
max_life_span             50
gestation_time            28
predation_index            2
sleep_exposure_index       2
danger_index               2
total_sleep              8.6
Name: 3.0, dtype: object

In [254]:
sleeps["total_sleep"]

body_weight
6654.000     3.3
1.000        8.3
3.385       12.5
0.920       16.5
2547.000     3.9
            ...
2.000        5.4
0.104       15.8
4.190       10.3
3.500       19.4
4.050          ?
Name: total_sleep, Length: 62, dtype: str

In [255]:
sleeps.get("total_sleep")

body_weight
6654.000     3.3
1.000        8.3
3.385       12.5
0.920       16.5
2547.000     3.9
            ...
2.000        5.4
0.104       15.8
4.190       10.3
3.500       19.4
4.050          ?
Name: total_sleep, Length: 62, dtype: str

In [256]:
sleep.drop(columns=['gestation_time'])

,body_weight,brain_weight,max_life_span,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,3,5,3,3.3
1,1.000,6.6,4.5,3,1,3,8.3
2,3.385,44.5,14,1,1,1,12.5
3,0.920,5.7,?,5,2,3,16.5
4,2547.000,4603.0,69,3,5,4,3.9
...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,3,1,3,5.4
58,0.104,2.5,2.3,3,2,2,15.8
59,4.190,58.0,24,4,3,4,10.3
60,3.500,3.9,3,2,1,1,19.4
61,4.050,17.0,13,3,1,1,?

In [257]:
sleeps.astype({'predation_index':'float64'})

,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
body_weight,,,,,,,
6654.000,5712.0,38.6,645,3.0,5,3,3.3
1.000,6.6,4.5,42,3.0,1,3,8.3
3.385,44.5,14,60,1.0,1,1,12.5
0.920,5.7,?,25,5.0,2,3,16.5
2547.000,4603.0,69,624,3.0,5,4,3.9
...,...,...,...,...,...,...,...
2.000,12.3,7.5,200,3.0,1,3,5.4
0.104,2.5,2.3,46,3.0,2,2,15.8
4.190,58.0,24,210,4.0,3,4,10.3
3.500,3.9,3,14,2.0,1,1,19.4
4.050,17.0,13,38,3.0,1,1,?

In [258]:
renamedcolumns={"sleep_exposure_index":"exposure_index"}
sleep.rename(columns=renamedcolumns)

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [259]:
sleep.isnull().sum()

body_weight             0
brain_weight            0
max_life_span           0
gestation_time          0
predation_index         0
sleep_exposure_index    0
danger_index            0
total_sleep             0
dtype: int64

In [260]:
sleeps=sleep.dropna(subset=['brain_weight'])

In [261]:
sleep.isnull().sum()

body_weight             0
brain_weight            0
max_life_span           0
gestation_time          0
predation_index         0
sleep_exposure_index    0
danger_index            0
total_sleep             0
dtype: int64

In [262]:
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [263]:
average=round(sleep['predation_index'].mean())
print(average)

3

In [264]:
sleep['predation_index']=sleep['predation_index'].fillna(average)
sleep.isnull().sum()

body_weight             0
brain_weight            0
max_life_span           0
gestation_time          0
predation_index         0
sleep_exposure_index    0
danger_index            0
total_sleep             0
dtype: int64

In [265]:
duplicates=sleep[sleep.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [body_weight, brain_weight, max_life_span, gestation_time, predation_index, sleep_exposure_index, danger_index, total_sleep]
Index: []

In [266]:
sleep.drop_duplicates()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [267]:
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [268]:
sleep['predation_index'].unique

<bound method Series.unique of 0     3
1     3
2     1
3     5
4     3
     ..
57    3
58    3
59    4
60    2
61    3
Name: predation_index, Length: 62, dtype: int64>

In [269]:
sleep['predation_index'].value_counts()

predation_index
2    15
1    14
5    14
3    12
4     7
Name: count, dtype: int64

In [270]:
sleep['predation_index'].value_counts().idxmax()

np.int64(2)

In [271]:
sleep['predation_index'].value_counts().idxmin()

np.int64(4)

In [272]:
sleep.sort_index()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [273]:
sleep=sleep.assign(increased_body_weight=sleep['body_weight']*2)
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep,increased_body_weight
0,6654.000,5712.0,38.6,645,3,5,3,3.3,13308.000
1,1.000,6.6,4.5,42,3,1,3,8.3,2.000
2,3.385,44.5,14,60,1,1,1,12.5,6.770
3,0.920,5.7,?,25,5,2,3,16.5,1.840
4,2547.000,4603.0,69,624,3,5,4,3.9,5094.000
...,...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4,4.000
58,0.104,2.5,2.3,46,3,2,2,15.8,0.208
59,4.190,58.0,24,210,4,3,4,10.3,8.380
60,3.500,3.9,3,14,2,1,1,19.4,7.000
61,4.050,17.0,13,38,3,1,1,?,8.100

In [274]:
sleep['body_weight']=sleep['body_weight'].apply (lambda x:x*1.5)
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep,increased_body_weight
0,9981.0000,5712.0,38.6,645,3,5,3,3.3,13308.000
1,1.5000,6.6,4.5,42,3,1,3,8.3,2.000
2,5.0775,44.5,14,60,1,1,1,12.5,6.770
3,1.3800,5.7,?,25,5,2,3,16.5,1.840
4,3820.5000,4603.0,69,624,3,5,4,3.9,5094.000
...,...,...,...,...,...,...,...,...,...
57,3.0000,12.3,7.5,200,3,1,3,5.4,4.000
58,0.1560,2.5,2.3,46,3,2,2,15.8,0.208
59,6.2850,58.0,24,210,4,3,4,10.3,8.380
60,5.2500,3.9,3,14,2,1,1,19.4,7.000
61,6.0750,17.0,13,38,3,1,1,?,8.100

In [275]:
sleep['predation_index']=sleep['predation_index'].map({
    1:'ONE',
    2:"TWO",
    3:'THREE',
    4:"FOUR",
    5:"FIVE"
})
sleep

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep,increased_body_weight
0,9981.0000,5712.0,38.6,645,THREE,5,3,3.3,13308.000
1,1.5000,6.6,4.5,42,THREE,1,3,8.3,2.000
2,5.0775,44.5,14,60,ONE,1,1,12.5,6.770
3,1.3800,5.7,?,25,FIVE,2,3,16.5,1.840
4,3820.5000,4603.0,69,624,THREE,5,4,3.9,5094.000
...,...,...,...,...,...,...,...,...,...
57,3.0000,12.3,7.5,200,THREE,1,3,5.4,4.000
58,0.1560,2.5,2.3,46,THREE,2,2,15.8,0.208
59,6.2850,58.0,24,210,FOUR,3,4,10.3,8.380
60,5.2500,3.9,3,14,TWO,1,1,19.4,7.000
61,6.0750,17.0,13,38,THREE,1,1,?,8.100

In [276]:
sleep.groupby("predation_index")['body_weight'].mean()

predation_index
FIVE      220.187250
FOUR       80.745214
ONE        65.885143
THREE    1156.070500
TWO         2.959500
Name: body_weight, dtype: float64

In [277]:
sleep.groupby("danger_index")['max_life_span'].max()

danger_index
1      ?
2      ?
3      ?
4    7.6
5     46
Name: max_life_span, dtype: str

In [278]:
sleep[sleep['danger_index']==1]

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep,increased_body_weight
2,5.0775,44.50,14,60,ONE,1,1,12.5,6.770
6,0.0345,0.30,19,35,ONE,1,1,19.7,0.046
8,4.9500,25.60,28,63,ONE,2,1,14.5,6.600
9,78.2400,440.00,50,230,ONE,1,1,9.7,104.320
14,0.1125,1.20,3.5,42,ONE,1,1,8.4,0.150
18,2.1150,17.50,34,?,ONE,2,1,6.1,2.820
19,90.0000,81.00,7,?,ONE,1,1,18.1,120.000
23,310.5000,406.00,39.3,252,ONE,4,1,12,414.000
24,127.5000,325.00,41,310,ONE,3,1,6.2,170.000
25,54.4950,119.50,16.2,63,ONE,1,1,13,72.660
29,150.0000,157.00,22.4,100,ONE,1,1,10.8,200.000
32,0.0150,0.25,24,50,ONE,1,1,19.9,0.020
33,93.0000,1320.00,100,267,ONE,1,1,8,124.000
34,0.1830,3.00,?,30,TWO,1,1,10.6,0.244
38,2.5500,6.30,5,12,TWO,1,1,19.4,3.400
39,5.2500,10.80,6.5,120,TWO,1,1,17.4,7.000
48,6.3525,50.40,9.8,52,ONE,1,1,9.8,8.470
60,5.2500,3.90,3,14,TWO,1,1,19.4,7.000
61,6.0750,17.00,13,38,THREE,1,1,?,8.100

In [279]:
sleep[sleep['body_weight']==5.0775]

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep,increased_body_weight
2,5.0775,44.5,14,60,ONE,1,1,12.5,6.77

In [280]:
sleep.sort_values("max_life_span",ascending=False)

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep,increased_body_weight
12,0.8250,2.4,?,?,TWO,1,2,10.3,1.100
35,2.0250,8.1,?,45,THREE,1,3,11.2,2.700
34,0.1830,3.0,?,30,TWO,1,1,10.6,0.244
3,1.3800,5.7,?,25,FIVE,2,3,16.5,1.840
48,6.3525,50.4,9.8,52,ONE,1,1,9.8,8.470
...,...,...,...,...,...,...,...,...,...
61,6.0750,17.0,13,38,THREE,1,1,?,8.100
54,2.1000,12.5,12.7,90,TWO,2,2,11,2.800
41,0.7200,15.5,12,140,TWO,2,2,17,0.960
33,93.0000,1320.0,100,267,ONE,1,1,8,124.000
17,0.3000,5.0,10.4,120,TWO,2,2,10.7,0.400